I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 7, in script
    image mc = mc.png
  File "game/script.rpy", line 7, in <module>
    image mc = mc.png
AttributeError: 'ADVCharacter' object has no attribute 'png'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 7, in script
    image mc = mc.png
  File "/Users/zjackson1233/Documents/renpy-8.3.4-sdk/renpy/ast.py", line 926, in execute
    img = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "/Users/zjackson1233/Documents/renpy-8.3.4-sdk/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 7, in <module>
    image mc = mc.png
AttributeError: 'ADVCharacter' object has no attribute 'png'

macOS-12.7.5-arm64-arm-64bit arm64
Ren'Py 8.3.4.24120703
Game 1.0
Tue Jan  7 09:24:03 2025
